#jingz's simple file to test makeFile
allTarget:p23_va_args_target
	g++ p23_va_args.o -o p23_va_args.exe
#remove the object files
	rm -rf p23_va_args.o
#complie the cpps into objects
p23_va_args_target:
	g++ -std=c++11 -c p23_va_args.cpp -o p23_va_args.o

